INSERT INTO categoria (nome_categ,tipo_categ) VALUES
("Vodka","bebida"),
("Whisky","bebida"),
("Cachaça","bebida"),
("Cerveja","bebida"),
("Gin","bebida"),
("Licor","bebida"),
("Saque","bebida"),
("Tequila","bebida"),
("Rum","bebida"),
("Vinho","bebida"),
("Espumante","bebida"),
("Champanhe","bebida"),
("Hidromel","bebida"),
("Sidra","bebida"),
("Conhaque","bebida"),
("Vermute","bebida"),
("Brandy","bebida"),
("Martini","bebida"),
("Grappa","bebida"),
("Energético","bebida"),
("Refrigerante","bebida"),
("Suco","bebida"),
("Xarope","bebida"),
("Chá","bebida"),
("Calda","bebida"),
("Outros","bebida"),
("Abridor","acessorio"),
("Dosador","acessorio"),
("Balde","acessorio"),
("Biqueira","acessorio"),
("Coador","acessorio"),
("Colher","acessorio"),
("Cortador","acessorio"),
("Espremedor","acessorio"),
("Fôrma","acessorio"),
("Macerador","acessorio"),
("Mixer","acessorio"),
("Coqueteleira","acessorio"),
("Pegador","acessorio"),
("Pá de Gelo","acessorio"),
("Copo","acessorio"),
("Taça","acessorio"),
("Caneca","acessorio"),
("Jarra","acessorio"),
("Outros","acessorio")


